

export const Details = {
   Traiteur : {
      ar : "بصفتنا متعهد تقديم طعام محترف ، فإننا نقدم مجموعة واسعة من خدمات الطهي لتلبية احتياجات الحدث الخاصة بك. نحن متخصصون في إعداد وتقديم وجبات الطعام وخدمات التموين للمناسبات المختلفة مثل حفلات الزفاف وأعياد الميلاد وحفلات الاستقبال والمؤتمرات واجتماعات العمل وأكثر من ذلك بكثير. تشمل خدمات تقديم الطعام لدينا تصميم قائمة مخصصة لتناسب تفضيلاتك ومتطلباتك الغذائية المحددة. نستخدم مكونات عالية الجودة لإعداد أطباق لذيذة وجذابة ترضي أذواق ضيوفك. يقوم فريقنا من الطهاة ذوي الخبرة بتطبيق تقنيات طهي متقدمة لضمان تحضير كل طبق بعناية واهتمام بالتفاصيل.",
      fr : " En tant que traiteur professionnel, nous offrons un large éventail de services culinaires pour répondre à vos besoins événementiels spécifiques. Nous sommes spécialisés dans la préparation et la fourniture de repas et de services de restauration pour divers événements tels que des mariages, des anniversaires, des réceptions, des conférences, des réunions d'affaires et bien plus encore. Nos services de traiteur comprennent la conception de menus personnalisés pour s'adapter à vos préférences et à vos exigences alimentaires spécifiques. Nous utilisons des ingrédients de qualité supérieure pour préparer des plats savoureux et attrayants qui satisferont les palais de vos invités. Notre équipe de chefs expérimentés met en œuvre des techniques culinaires avancées pour garantir que chaque plat est préparé avec soin et attention aux détails.",
   },
   Team : {
      ar : " لوريم ايبسوم دولار سيت أميت ,كونسيكتيتور أدايبا يسكينج أليايت,سيت دو أيوسمود تيمبور أنكايديديونتيوت لابوري ات دولار ماجنا أليكيوا . يوت انيم أد مينيم فينايم,كيواس نوستريد أكسير سيتاشن يللأمكو لابورأس نيسي يت أليكيوب أكس أيا كوممودو كونسيكيوات . ديواس أيوتي أريري دولار إن ريبريهينديرأيت فوليوبتاتي فيلايت أيسسي كايلليوم دولار أيو فيجايت نيولا باراياتيور. أيكسسيبتيور ساينت أوككايكات كيوبايداتات نون بروايدينت ,سيونت ان كيولباو أوفيسيا ديسيريونتموليت انيم أيدي ايست لابوريوم بصفتنا متعهد تقديم طعام محترف ، فإننا نقدم مجموعة واسعة من خدمات الطهي لتلبية احتياجات الحدث الخاصة بك. نحن متخصصون في إعداد وتقديم وجبات الطعام وخدمات التموين للمناسبات المختلفة مثل حفلات الزفاف وأعياد الميلاد وحفلات الاستقبال والمؤتمرات واجتماعات العمل وأكثر من ذلك بكثير. تشمل خدمات تقديم الطعام لدينا تصميم قائمة مخصصة لتناسب تفضيلاتك ومتطلباتك الغذائية المحددة. نستخدم مكونات عالية الجودة لإعداد أطباق لذيذة وجذابة ترضي أذواق ضيوفك. يقوم فريقنا من الطهاة ذوي الخبرة بتطبيق تقنيات طهي متقدمة لضمان تحضير كل طبق بعناية واهتمام بالتفاصي",
      fr : " Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum",
   },
   Restauration : {
      ar : " لوريم ايبسوم دولار سيت أميت ,كونسيكتيتور أدايبا يسكينج أليايت,سيت دو أيوسمود تيمبور أنكايديديونتيوت لابوري ات دولار ماجنا أليكيوا . يوت انيم أد مينيم فينايم,كيواس نوستريد أكسير سيتاشن يللأمكو لابورأس نيسي يت أليكيوب أكس أيا كوممودو كونسيكيوات . ديواس أيوتي أريري دولار إن ريبريهينديرأيت فوليوبتاتي فيلايت أيسسي كايلليوم دولار أيو فيجايت نيولا باراياتيور. أيكسسيبتيور ساينت أوككايكات كيوبايداتات نون بروايدينت ,سيونت ان كيولباو أوفيسيا ديسيريونتموليت انيم أيدي ايست لابوريوم بصفتنا متعهد تقديم طعام محترف ، فإننا نقدم مجموعة واسعة من خدمات الطهي لتلبية احتياجات الحدث الخاصة بك. نحن متخصصون في إعداد وتقديم وجبات الطعام وخدمات التموين للمناسبات المختلفة مثل حفلات الزفاف وأعياد الميلاد وحفلات الاستقبال والمؤتمرات واجتماعات العمل وأكثر من ذلك بكثير. تشمل خدمات تقديم الطعام لدينا تصميم قائمة مخصصة لتناسب تفضيلاتك ومتطلباتك الغذائية المحددة. نستخدم مكونات عالية الجودة لإعداد أطباق لذيذة وجذابة ترضي أذواق ضيوفك. يقوم فريقنا من الطهاة ذوي الخبرة بتطبيق تقنيات طهي متقدمة لضمان تحضير كل طبق بعناية واهتمام بالتفاصي",
      fr : " Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum", 
   },
}
